version: "3.8"

services:
  web:
    build: docker/
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nextjs_try
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
